# Generated by Django 5.0.6 on 2024-06-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentEquity',
            fields=[
                ('name_and_surname', models.CharField(max_length=64, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('job_title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('race', models.CharField(choices=[('African', 'African'), ('Indian', 'Indian'), ('Coloured', 'Coloured'), ('Non-Black', 'Non-Black')], max_length=64, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=64, null=True)),
                ('disabled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('description_of_disability', models.CharField(max_length=150, null=True)),
                ('occupational_level', models.CharField(choices=[('Junior Management', 'Junior Management'), ('Middle Management', 'Middle Management'), ('Senior Management', 'Senior Management'), ('Executive Management', 'Executive Management'), ('Other Executive Management', ' Other Executive Management'), ('Semi-Skilled', 'Semi-Skilled')], max_length=64, null=True)),
                ('foreign', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('pilot', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('technician', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('black_youth_as_defined_by_the_national_youth_commission_act_of_1996', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
            ],
        ),
    ]
