# Generated by Django 5.0.6 on 2024-06-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0002_employmentequity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('name_and_surname', models.CharField(max_length=64, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('race', models.CharField(choices=[('African', 'African'), ('Indian', 'Indian'), ('Coloured', 'Coloured'), ('Non-Black', 'Non-Black')], max_length=64, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=64, null=True)),
                ('disabled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('job_title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('voting_rights', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('executive_director', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('independent_non_Executive', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=64, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('race', models.CharField(choices=[('African', 'African'), ('Indian', 'Indian'), ('Coloured', 'Coloured'), ('Non-Black', 'Non-Black')], max_length=64, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=64, null=True)),
                ('disabled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('foreign', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('designated_groups', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('youth', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('unemployed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('living_in_rural_areas', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('military_veteran', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('economic_interest', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('voting_rights', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('chartered_accountant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('outstanding_debt_by_black_participants', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=64, null=True)),
                ('reg_no', models.IntegerField(blank=True, null=True)),
                ('expenditure_per_supplier_ledger_for_the_period_including_vat', models.FloatField(blank=True, null=True)),
                ('expenditure_excluding_vat', models.FloatField(blank=True, null=True)),
                ('non_vat_item', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('supplier_classification', models.CharField(choices=[('Generic', 'Generic'), ('QSE', 'QSE'), ('EME', 'EME')], max_length=64, null=True)),
                ('bee_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('Non Compliant', 'Non Compliant')], max_length=64, null=True)),
                ('fifty_one_percent_or_more_black_owned', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('black_ownership_percent', models.FloatField(blank=True, null=True)),
                ('thirty_percent_or_more_black_woman_owned', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('black_woman_ownership', models.FloatField(blank=True, null=True)),
                ('empowering_supplier', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('esd_recipient_and_black_owned_qse_or_eme_min_three_year_contract', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('designated_group_supplier', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=64, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('race', models.CharField(choices=[('African', 'African'), ('Indian', 'Indian'), ('Coloured', 'Coloured'), ('Non-Black', 'Non-Black')], max_length=64, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=64, null=True)),
                ('disabled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('training_course', models.CharField(max_length=64, null=True)),
                ('trainer_or_service_provider', models.CharField(max_length=64, null=True)),
                ('category', models.CharField(choices=[('A', 'A'), ('A2', 'A2'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('MST', 'MST')], max_length=64, null=True)),
                ('internal_training', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('abet', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('abet_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=64, null=True)),
                ('core_and_or_critical_skills', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('direct_expenditure_for_period_excl_vat', models.FloatField(blank=True, null=True)),
                ('additional_expenditure_for_the_period', models.FloatField(blank=True, null=True)),
                ('total_expenditure', models.FloatField(blank=True, null=True)),
                ('cost_to_company_annual_salary_for_b_c_d_students', models.FloatField(blank=True, null=True)),
                ('duration_of_training_in_hours_for_internal_training', models.FloatField(blank=True, null=True)),
                ('cost_to_company_annual_salary_for_internal_trainers_category_g', models.FloatField(blank=True, null=True)),
                ('number_of_participants_on_training_course_category_g', models.IntegerField(blank=True, null=True)),
                ('designated_groups', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('passed_qualifying_examinations', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('spare', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('unemployed_learner', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('absorbed_learner', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
            ],
        ),
    ]
