# Generated by Django 5.0.6 on 2024-06-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0003_board_ownership_procurement_skillsdevelopment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentequity',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='job_title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employmentequity',
            name='job_title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
