# Generated by Django 5.0.6 on 2024-06-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0005_alter_board_id_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinacialSkillsDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finacial_period', models.CharField(max_length=64, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('sdl_payments_made_per_emp201', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_period', models.CharField(max_length=64, null=True)),
                ('turnover_revenue', models.FloatField(blank=True, null=True)),
                ('nett_profit_before_tax', models.FloatField(blank=True, null=True)),
                ('nett_profit_after_tax', models.FloatField(blank=True, null=True)),
                ('salaries', models.FloatField(blank=True, null=True)),
                ('directors_members_emoluments', models.FloatField(blank=True, null=True)),
                ('annual_payroll', models.FloatField(blank=True, null=True)),
                ('expenses', models.FloatField(blank=True, null=True)),
                ('cost_of_sales_purchases_only', models.FloatField(blank=True, null=True)),
                ('additions_capex_for_the_year', models.FloatField(blank=True, null=True)),
                ('depreciation_for_the_year', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetProfit_ED_ESD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finacial_period', models.CharField(max_length=64, null=True)),
                ('npat', models.FloatField(blank=True, null=True)),
                ('projected', models.FloatField(blank=True, null=True)),
                ('ed', models.FloatField(blank=True, null=True)),
                ('sd', models.FloatField(blank=True, null=True)),
                ('sed', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocioEconomicDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(max_length=64, null=True)),
                ('ict_sector_initiative', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('black_participation_percent', models.FloatField(blank=True, null=True)),
                ('contribution_type', models.CharField(choices=[('Direct Cost', 'Direct Cost'), ('Non-Monetary', 'Non-Monetary')], max_length=64, null=True)),
                ('description_of_contribution', models.CharField(max_length=64, null=True)),
                ('structured_sed_project', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64, null=True)),
                ('date_of_contribution', models.DateField(null=True)),
                ('amount_of_contribution', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_method', models.CharField(max_length=64, null=True)),
                ('formal_valuation_if_available', models.FloatField(blank=True, null=True)),
                ('total_assets', models.FloatField(blank=True, null=True)),
                ('total_liabilities', models.FloatField(blank=True, null=True)),
                ('nett_asset_value_per_afs', models.FloatField(blank=True, null=True)),
                ('finacial_period', models.CharField(max_length=64, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ownership',
            name='ownership_model',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
