# Generated by Django 5.0.6 on 2024-07-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0006_finacialskillsdevelopment_financialinformation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentequity',
            old_name='name_and_surname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='employmentequity',
            name='ingest_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employmentequity',
            name='surname',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employmentequity',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
