# Generated by Django 5.0.6 on 2024-07-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0007_rename_name_and_surname_employmentequity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentequity',
            name='ingest_date',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
