# Generated by Django 5.0.6 on 2024-07-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0011_rename_black_youth_as_defined_by_the_national_youth_commission_act_of_1996_employmentequity_black_yo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentequity',
            old_name='Occupational_level',
            new_name='Occupational_Level',
        ),
        migrations.AddField(
            model_name='employmentequity',
            name='Gross_Monthly_Salary',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
