# Generated by Django 5.0.6 on 2024-07-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0012_rename_occupational_level_employmentequity_occupational_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentequity',
            old_name='Id_number',
            new_name='Id_Number',
        ),
    ]
