# Generated by Django 5.0.6 on 2024-07-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0013_rename_id_number_employmentequity_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socioeconomicdevelopment',
            old_name='amount_of_contribution',
            new_name='Amount_of_Contribution',
        ),
        migrations.RenameField(
            model_name='socioeconomicdevelopment',
            old_name='beneficiary',
            new_name='Beneficiary',
        ),
        migrations.RenameField(
            model_name='socioeconomicdevelopment',
            old_name='contribution_type',
            new_name='Contribution_Type',
        ),
        migrations.RenameField(
            model_name='socioeconomicdevelopment',
            old_name='date_of_contribution',
            new_name='Date_of_Contribution',
        ),
        migrations.RenameField(
            model_name='socioeconomicdevelopment',
            old_name='description_of_contribution',
            new_name='Description_of_Contribution',
        ),
        migrations.RenameField(
            model_name='socioeconomicdevelopment',
            old_name='ict_sector_initiative',
            new_name='Ict_Sector_Initiative',
        ),
        migrations.RenameField(
            model_name='socioeconomicdevelopment',
            old_name='black_participation_percent',
            new_name='Percentage_of_Black_participation',
        ),
        migrations.RenameField(
            model_name='socioeconomicdevelopment',
            old_name='structured_sed_project',
            new_name='Structured_SED_Project',
        ),
        migrations.RemoveField(
            model_name='socioeconomicdevelopment',
            name='id',
        ),
        migrations.AddField(
            model_name='socioeconomicdevelopment',
            name='Ingest_date',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomicdevelopment',
            name='Table_Name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomicdevelopment',
            name='ID',
            field=models.CharField(default=1, max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
